Choose a kickstart:

 [ safe              ] boot from local disk
 [ coreos            ] PXE-boot CoreOS
 [ rhel-rescue       ] rescue RHEL
 [ rhel-5.5          ] install RHEL 5.5 64-bit
 [ rhel-5.7-32       ] install RHEL 5.7 32-bit
 [ rhel-6.3          ] install RHEL 6.3 64-bit
 [ rhel-6.5          ] install RHEL 6.5 64-bit
 [ rhel-7.0          ] install RHEL 7.0 64-bit
 [ windows           ] install all Windows OS
